### ISSUE TITLE
TODO section does not show, magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.

### ISSUE THREAD

**Issue by citypilgrim** [alphapapa/magit-todos#119]
I am currently using 

1. Magit 3.1.1
2. Magit-todos 1.5.3

My configuration for both packages are as such
```
  (use-package magit
    :commands (magit-status magit-get-current-branch)
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (use-package magit-todos
    :ensure t
    :commands (magit-todos-mode)
    :config
    (setq magit-todos-recursive t
          magit-todos-depth 100))
```
---
When I start emacs, I notice that the the variable `magit-todos-mode` is nil.
When I enter the `magit-status-buffer` I am not able to see nor jump to the TODOs section. 
Exiting the status buffer, I enable `magit-todos-mode` but am met with the error `magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.`
Upon reentering the buffer, there is still no TODOs section.

**Comment by alphapapa** [comment]
> When I start emacs, I notice that the the variable `magit-todos-mode` is nil.

Because you haven't enabled `magit-todos-mode`.

> When I enter the `magit-status-buffer` I am not able to see nor jump to the TODOs section.

Because you haven't enabled `magit-todos-mode`.

> Exiting the status buffer, I enable `magit-todos-mode` but am met with the error `magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.`

That's not an error, it's just informative.

> Upon reentering the buffer, there is still no TODOs section.

"Exit" and "reenter" are not Emacs jargon related to buffers.  Buffers may be created, switched to, and killed.  I don't know what you mean by "exit" and "reenter," so I don't know exactly what you did.

Anyway, no TODOs section will be displayed unless there are items found to display.

I just re-verified that this package works correctly when installed into a clean Emacs configuration.  So there is no bug here.

**Comment by mmahmoudian** [comment]
I am facing "similar" issue. I think even when the depth is set, somehow the rg is not called with the depth. To make sure this is not an issue with my config, I ran `emacs -Q` and then:


```elisp
;; add melpa
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
;(package-refresh-contents)
(package-initialize)

;; install use-package if needed
(unless (package-installed-p 'use-package)
    (package-install 'use-package))
(setq use-package-always-ensure t)
(require 'use-package)


;; some encoding stuff
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)


;; tell the dependency what to look for
(use-package hl-todo
  :ensure t
  :config
   (setq hl-todo-keyword-faces
	'(("TODO"   . "#FF0000")
	  ("FIXME"  . "#FF0000")
	  ("DEBUG"  . "#A020F0")
	  ("GOTCHA" . "#FF4500")
	  ("STUB"   . "#1E90FF")))
   :hook (
          (prog-mode . hl-todo-mode)
          ))
;; magit
(use-package magit
  :ensure t)

;; magit-todo with some minor settings
(use-package magit-todos
  :ensure t
  :config
  ;; TODO: do some stuff
    (setq magit-todos-depth 100)
  :hook (
         (magit-mode . magit-todos-mode)
         ))
```

I then created a nested folder structure (as the top right buffer shows), each with a todo, but it still only get the depth 0:

![image](https://user-images.githubusercontent.com/390889/208118403-32276b58-6d98-4381-95e4-8ee4a82a2e0e.png)

**Comment by alphapapa** [comment]
@mmahmoudian Please note carefully in the `rg` output the difference between the TODO items that are displayed and those in the nested subdirectories that are not displayed.  It appears that even `rg` can't read those files properly.  Meanwhile, if you were to put the `init.el` file in a subdirectory, or a valid source code file, it would be displayed.

If you still think there is a bug to be fixed, please open a new issue.

**Comment by mmahmoudian** [comment]
@alphapapa Thanks for the reply.

>  It appears that even `rg` can't read those files properly. 

Actually `rg` red them properly, the text `file[123]` are exactly as displayed in the picture above, and `rg` correctly is showing them (`blah blah\nTODO: something\nblah`). But then I had a hunch based on your comment and I kept digging. It turned out that adding a space between `\nTODO` make the `magit-todos` to find it, but adding a non-white-space character would not work. For example `#TODO`  or `;TODO` (which are common comment characters) are not detected:

![image](https://user-images.githubusercontent.com/390889/208425319-86f7633d-21be-40e5-be45-69ebf20f5ccc.png)

<sup>I copied the `init.el` to every sub folder to demo that `magit-todos` goes deep enough and my hypothesis in the previous comment in this thread is invalid. So you can safely ignore all detected instances of `init.el` and only focus on `file2`</sup>

I'm not sure if this is a bug, or intended behavior or something that can be requested via a feature request. If it can be requested, I would be more than happy to file e feature request with some implementation suggestion.

**Comment by alphapapa** [comment]
@mmahmoudian Please see #125, #135, and #136.
