### ISSUE TITLE
help wanted: no todos appear in magit's todo list

### ISSUE THREAD

**Issue by JonatanSahar** [alphapapa/magit-todos#146]
Hi,
I've verified that `magit-todos-mode` is set to `t`, and that I have rg installed and working on my system (windows), but I get no results in either org-mode org code projects. 
Any idea how to proceed?

Thanks!

**Comment by alphapapa** [comment]
Hello,

I've seen issues like this reported many times.  Usually it is a case of incorrect configuration and/or misunderstanding of how the package works.  Please search the issues list (open and closed) for similar discussions.  You should be able to find answers that way.  This package is known to work correctly, and I don't really have time to do step-by-step troubleshooting for each user, especially on proprietary platforms.  Otherwise, please ask on an Emacs help forum, such as https://old.reddit.com/r/emacs, because this is an issue tracker, not a support forum.  Thanks.
