### ISSUE TITLE
Persistent error when running `magit-status` in an empty Git repository

### ISSUE THREAD

**Issue by abougouffa** [alphapapa/magit-todos#167]
Hello,

First, let me thank you for this amazing package!

I've noticed that, after initializing a new Git repo (and even, after pushing some commits that only adds hidden files), `magit-todos` displays an error when we `M-x magit-status`.

This is the backtrace:

```elisp
Debugger entered--Lisp error: (error "magit-todos--async-when-done: Process \"magit-todos--scan-with-rg\" failed with exit code 2.  Output:\"rg: No files were searched, which means ripgrep probably applied a filter you didn't expect.\nRunning with --debug will show why files are being skipped.\n\"")
  signal(error ("magit-todos--async-when-done: Process \"magit-todos--scan-with-rg\" failed with exit code 2.  Output:\"rg: No files were searched, which means ripgrep probably applied a filter you didn't expect.\nRunning with --debug will show why files are being skipped.\n\""))
  error("magit-todos--async-when-done: Process %S failed wi..." "magit-todos--scan-with-rg" 2 "rg: No files were searched, which means ripgrep probably applied a filter you didn't expect.\nRunning with --debug will show why files are being skipped.\n")
  magit-todos--async-when-done(#<process magit-todos--scan-with-rg> "exited abnormally with code 2\n")
```

#### `M-x emacs-version`
```
GNU Emacs 29.1.90 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.39, cairo version 1.18.0) of 2023-12-24
```
#### `git --version`
```
git version 2.43.0
```
#### `rg --version`
```
ripgrep 14.1.0

features:-simd-accel,+pcre2
simd(compile):+SSE2,-SSSE3,-AVX2
simd(runtime):+SSE2,+SSSE3,+AVX2

PCRE2 10.42 is available (JIT is available)
```
#### `fd --version`
```
fd 9.0.0
```

**Comment by alphapapa** [comment]
Hello,

Thanks for the kind words.  I'm glad this package is useful to you.

Regarding the error, I'm not sure what to do here.  As the output of `rg` shows: `rg: No files were searched`, which is unexpected, and would probably indicate a problem in most cases, hence an error.  Since most git repositories will probably not remain empty, is it necessary to specially handle this case and not signal an error?  As well, this package has been around for nearly 6 years, and despite the many problems that have been reported here, this is the first report of this particular problem.

What do you think?  Thanks.

**Comment by abougouffa** [comment]
Hi @alphapapa ,

Well I do agree, I'm using the package for two years and today is the first time it happened. So, yes, I think I can live with that!

Thanks again!
