### ISSUE TITLE
Feature request: show which TODOs were added in current branch

### ISSUE THREAD

**Issue by itamarst** [alphapapa/magit-todos#30]
First, this is pretty cool!

Second: codebase currently has lots of TODOs. I mostly want to focus on ones I added/removed in current branch, to see if I haven't skipped addressing any. So it would be nice if there was some way to see what TODOs were added/deleted in current branch.

Maybe equivalent commands to the magit `d` commands, so one could get todos diff dwim, todos diff range, etc.?

**Comment by alphapapa** [comment]
Glad you are liking it so far!

That's a really cool idea, but it sounds fairly complicated to integrate with Magit.  I think it would basically require running the scan on a diff of the current branch vs. master, and that would require saving the diff to a temp file (and perhaps removing the diff metadata), and running the scanner on just that file.  That sounds fairly straightforward, but 1) doing it without reimplementing much of what Magit does means digging into a lot of Magit's code, and 2) making the UI easy to use is also not...easy.  It seems like the kind of feature that belongs in a magit-popup UI, and that's an idea we've had, but we probably won't have that for a while.

So I think this would be a great feature to have, but I don't think I'll be implementing it anytime soon, probably not until we have a popup UI to go with it.  But patches are always welcome.  :)

Thanks.

**Comment by itamarst** [comment]
OK, thanks for the detailed response!

**Comment by alphapapa** [comment]
Also: When I wrote that I was only thinking about a single-file project.  Doing it for multiple files might mean writing an entire directory tree of diffs, which would be messy, and slow for large projects. In that case we might as well do the scanning from inside Emacs, which would obviate the external scanners. And we used to do that, but it was slow. 

However, maybe for this case, that would be the proper thing to do. Maybe we could run the scan directly inside a magit diff buffer, and get the filenames and line numbers from the text properties. Maybe it would be fast enough to be useful...

**Comment by zhaojiangbin** [comment]
Perhaps `git log -STODO --pickaxe-regex --patch fork-point..this-branch` can help? But it treats the pattern, 'TODO' here, as an "extended POSIX regular expression to match." In other words, not in the Perl-syntax.

From the output, the lines that contain the pattern can be found by match either `^\+.*TODO` or `^-.*TODO`, for example.

If it is required file names and line numbers in files can be parsed out of the output, too.

To know whether there are now more TODOs or less since the fork-point, the parsing result from the previous steps would need to be counted and summarized.

This feature will be very cool indeed. The implementation would probably take quite some effort, too.

**Comment by alphapapa** [comment]
That's a really interesting idea, thanks.  I wonder if we could also do something like diff the output of `git grep` on the cache/index and on the working tree...

**Comment by itamarst** [comment]
Sounds like this was implemented in 1.3-pre? Closing.

**Comment by alphapapa** [comment]
Haha, wow, I forgot about this issue.  I don't know why I thought it would be so complicated, when it turned out to be as simple as parsing `git diff` output.  I guess forgetting about it gave me a fresh perspective.  Thanks for your patience.  I'll add your name to the credits for suggesting the idea.  :)

**Comment by itamarst** [comment]
Thanks for all the work you do on this!
