### ISSUE TITLE
Optionally filter items not in comments

### ISSUE THREAD

**Issue by deftsp** [alphapapa/magit-todos#32]
For example:
```
-- copyed from spacemacs
(if (funcall pred var)
          (progn
            (when (boundp 'passed-tests) (setq passed-tests (1+ passed-tests)))
            (insert (format "*** PASS: %s\n" var)))
        (insert (propertize (format "*** FAIL: %s\n" var) 'font-lock-face 'font-lock-warning-face)))
```

The "FAIL:" will be treated as keyword entries

**Comment by alphapapa** [comment]
Yes, this is a known issue.  Unfortunately I don't think we can easily do anything about this, because the scanners (git grep, rg, grep) do simple regexp matching without any concern for the file's syntax.  We could try to make a more complicated regexp to avoid such cases, but that wouldn't work when strings span multiple lines.  We could have Emacs post-process matches, but that would require opening the file, parsing the syntax with the major-mode, and checking with `syntax-ppss`, which would be prohibitively slow.

Probably the best way to handle this is to remove "FAIL" from your list of keywords, at least in that repository with a dir-local variable.

If you have any other ideas, please let me know.

**Comment by deftsp** [comment]
How about get the `comment-start` and `comment-end` for  a major mode by the extension part of the filename?  It's do not need to open the file.

**Comment by alphapapa** [comment]
For single-line comment syntax, that might work. It would slow down the process, but it could be optional.

**Comment by alphapapa** [comment]
I'm still not sure if that's a good idea.  To get `comment-start` for a major mode, AFAIK we need a buffer in that major mode.  If there isn't one already, we'd have to make one, which means activating the major mode, and I don't want to do that, because that can have a lot of side effects.

**Comment by deftsp** [comment]
How about add a variable (or cache file) to save the `comment-start`  for known file extension?

**Comment by alphapapa** [comment]
> How about add a variable (or cache file) to save the comment-start for known file extension?

That feels very out-of-scope for this project.  And as we all know, cache invalidation is one of the 3 hardest things in programming.  :)

**Comment by alphapapa** [comment]
I'm going to close this issue, because I don't think it's practical to implement.
