### ISSUE TITLE
magit-todos keeps scanning after killing magit buffer

### ISSUE THREAD

**Issue by msherry** [alphapapa/magit-todos#33]
I have a *very* large repo that takes magit-todos a long time to scan. I can open magit, perform some action, and kill the buffer before magit-todos has finished (`*magit-todos--scan-with-git-grep*` is still generating output). It would be nice to kill this process upon killing of the magit buffer.

**Comment by alphapapa** [comment]
Yes, there's actually a to-do item in the notes file for this.  I'm not sure how to implement it yet.  Thanks.

**Comment by alphapapa** [comment]
@msherry I just pushed this branch which should fix this problem.  Please test and let me know how it works for you.  Thanks.

**Comment by msherry** [comment]
Sorry for the delay in testing this out. It doesn't seem to have helped, though -- I opened a `magit` directory on my repo, and then opened `*magit-todos--scan-with-git-grep*`. I then killed the magit buffer, which *buried* the scan buffer, but did not kill it.

I've tried this with both `magit-mode-bury-buffer` (<kbd>q</kbd> by default) and `kill-buffer`, with the same results.

**Comment by alphapapa** [comment]
> Sorry for the delay in testing this out. 

No problem!  :)

> I then killed the magit buffer, which buried the scan buffer, but did not kill it.

I'm not sure what you mean by "buried the scan buffer."  "Burying a buffer" is a technical term in Emacs.  :)  It wouldn't typically be possible to bury the scan process's buffer, because you'd have to manually switch to it, and manually bury it.

> I've tried this with both magit-mode-bury-buffer (q by default) 

The feature uses `kill-buffer-hook`, so it won't kill the scanner process when burying the status buffer.

> and kill-buffer, with the same results.

AFAIK it should work, but that doesn't mean that it will.  It seems that things are rarely as simple as they seem when dealing with processes in Emacs.

How did you test it?  Did you load the branch's file into a fresh Emacs instance?

Are you sure that the *process* remained alive as well as the buffer?  Or did the process get killed but not its buffer?  If the latter, are you sure that it was *that* process's buffer, and not one that might have been hanging around?

**Comment by alphapapa** [comment]
FYI I rebased the branch onto `master`.

**Comment by alphapapa** [comment]
I merged this to `master`, but I haven't tagged a stable release yet.  I'd like to get some more feedback on this feature first.

**Comment by alphapapa** [comment]
I haven't heard any bug reports, and I tagged this as stable, so I'm closing this now.  Please let me know if you have any issues with this feature.
