### ISSUE TITLE
Some projects never update using rg

### ISSUE THREAD

**Issue by muihlinn** [alphapapa/magit-todos#42]
It seems to work with some projects, but some others (larger) never update after request. 
rg works fine on the command line with same projects; git-grep works fine with all projects into magit-todos.

emacs 26.1.50, rg binaries from repo. Ubuntu 18.04 

config:
```
(require 'magit)
(require 'magit-todos)

(setq magit-todos-mode 't
      magit-todos-require-colon nil
      magit-todos-update nil
      magit-todos-depth 100
      magit-todos-nice nil
      magit-todos-scanner 'magit-todos--scan-with-rg )

```

**Comment by alphapapa** [comment]
Are you sure they never complete, or did you just not wait long enough?  Is
rg still running?

Please don't set those options using setq, because they are customization
settings. Use the customize interface.
Activate magit-todos-mode by running the command, not setting the variable.

**Comment by muihlinn** [comment]
With complete I means it does nothing after more than an hour, which I suspect, is failing quietly.

I've tried in a few repos with mixed results, most work, some not, one took several mins to display them (~2k todos) , but rg search there is almost instantaneous from command line in any repo.

Using atop I can see rg popping up. It finishes very quickly in the ones which "fails" without any hint or complain. rg's --debug doesn't bring up any output buffer, as it used to do with a "problematic" snap package.

PD: I started setting those variables via customize, made no difference with the problem, anyway as adviced, I moved back to customize.

**Comment by alphapapa** [comment]
> With complete I means it does nothing after more than an hour, which I suspect, it's failing quietly.

If `rg` (or whatever scanner you're using) is no longer running, and Emacs isn't blocked, then it's finished.

> I've tried in a few repos with mixed results, most work, some not, one took several mins to display them (~2k todos) , but rg search is almost instantaneous from command line in any repo.

That seems like several different issues:

>  I've tried in a few repos with mixed results, most work, some not.  Using atop I can see rg popping up. It finishes very quickly in the ones which "fails" without any hint or complain. rg's --debug doesn't bring up any output buffer, as it used to do with a "problematic" snap package.

I suspect this is because some repos use entries like "TODO:" and others plain "TODO", or other differences in how the items are formatted.

> one took several mins to display them (~2k todos), but rg search is almost instantaneous from command line in any repo.

That probably only takes that long when the files are not in the cache.  When I display to-dos for the Emacs repo, which has 1800+ items, when the files aren't cached, it takes about 10-15 seconds while the disk thrashes.  After that it takes less than 5 seconds.

> PD: I started setting those variables via customize, made no difference with the problem, anyway as adviced, I moved back to customize.

Some items can be safely set by `setq`, depending on their type.  But you would have to look at the `defcustom` to know whether it's safe.  And even then, the definition could change in a future update, and then it would be incorrect.  So in general you shouldn't use `setq` for them.

**Comment by muihlinn** [comment]
looks like cleaning (once more) all customizations finally did the trick
