### ISSUE TITLE
Dependency a.el has wrong version in MELPA Stable

### ISSUE THREAD

**Issue by Lydzje** [alphapapa/magit-todos#45]
When I try to install _magit-todos_ through MELPA, I get this error:

<code>Need package 'a-0.1.0', but only 0.1.0alpha4 is available</code>

I'm using:

* Melpa Stable
* Emacs 26.1
* KDE Neon

**Comment by alphapapa** [comment]
Hmm, I'm not sure what's going on here.  Other people have apparently installed it from MELPA Stable for a while now, so I've assumed that it's working.

The tags in https://github.com/plexus/a.el are like `v0.1.0alpha4` instead of, e.g. `0.1.0`.  I'm not sure why the author tagged an "alpha" for stable release.  I see that it was last updated in November, so maybe the author would consider tagging a `0.1.0` release now.  @plexus?  :)

In the meantime, you can install it from the non-stable repo.

**Comment by plexus** [comment]
v0.1.0 is out now.

**Comment by alphapapa** [comment]
Thank you!  Closing this now.  Let me know if there are any other issues.
