### ISSUE TITLE
Smarter way of adding key bindings

### ISSUE THREAD

**Issue by mkleehammer** [alphapapa/magit-todos#48]
I'm using Spacemacs, which uses evil, so the magit bindings for 'j' have been moved to 'J'.  A normal 'j' is used to go down a line.

I see you have code to not override "jT" if it is already set, but that's not helping in this case.  

Is there a smarter way to identify a better key to bind to?  For example, to look at another jump function like magit-jump-to-staged and see how it is bound?

If not, I'd be happy with either a way to stop the binding or even a way to undo it in my init.el.  
I tried unbinding, but I'm not that good with elisp and using `define-key` to bind "jT" to null didn't work

As you can imagine, using a key to move down and then it stopping is super annoying.  Thanks.

**Comment by alphapapa** [comment]
Hi,

Please see https://github.com/alphapapa/magit-todos/issues/31

**Comment by mkleehammer** [comment]
I did see #31, but there wasn't actually a solution that I could find there, other than someone is writing a 3rd party package I'd rather not use for a single key.

I tried setting "j" back to evil-line-down but had no luck.  Perhaps this is because the keybinding is being set every time magit-todos-mode is being toggled?  (Did I read the code right?). I don't know of a hook that would be run to undo the binding after you have set it.

Also, I'm not entirely sure what I would do to undo the binding.  I've tried evaluating some `define-key` expressions while in the status buffer, but I've never been able to undo it.  Do you have a suggestion for how to do so?

**Comment by alphapapa** [comment]
Well, I don't use Spacemacs or EVIL, and as I mentioned in #31, AFAICT the existing code shouldn't override existing binds.  If it does, I guess it's because of the way EVIL works, and I don't think its appropriate to work around that in this package.  Considering how "invasive" Spacemacs and EVIL are (not a slight against them--they are both great), I think that supporting them with a package like `evil-collection`, which handles key binds appropriately, is the best solution.

You might also find general.el helpful for defining EVIL-compatible key bindings.

Other than recommending those packages, I don't think there's much I can do about this.  If you arrive at a better solution, I'd be happy to add a note about it to the readme.

What do you think?

**Comment by mpereira** [comment]
People landing here from Google, the following should disable `magit-todos`'s evil-conflicting keybindings:

```emacs-lisp
(general-define-key
 :keymaps '(magit-todos-section-map magit-todos-item-section-map)
 "jT" nil
 "jl" nil
 "j" nil)
```

This would ideally be fixed in [evil-collection](https://github.com/emacs-evil/evil-collection/blob/master/modes/magit-todos/evil-collection-magit-todos.el). I might open a PR later.

**Comment by alphapapa** [comment]
@mpereira Please do open that PR.  It's disappointing that `evil-collection` is supposed to support `magit-todos` but apparently doesn't (or needs updating).  It needs an EVIL user to contribute the fix, and I'm not one.

**Comment by mpereira** [comment]
@alphapapa I have a TODO entry scheduled for the near future. 🙂
