### ISSUE TITLE
error in process sentinel: magit-todos--line-item: Stack overflow in regexp matcher

### ISSUE THREAD

**Issue by lbolla** [alphapapa/magit-todos#63]
I am getting this error when enabling `magit-todos` in one of my repos:
```error in process sentinel: magit-todos--line-item: Stack overflow in regexp matcher```

I can't find the offending line/regex. `magit-todos-keyword-suffix` is configured to be just ":" (column).

Any idea how I can debug this more?

**Comment by alphapapa** [comment]
Please try to reproduce in the same repo using `emacs -q`, to confirm that it's not a configuration issue.  Thanks.

**Comment by lbolla** [comment]
Same results. I did `emacs -q`. Then loaded `magit` and `magit-todos` (with `(require ...)`) and then did `magit` on my repo (and `magit-todos-list`).

Same error.

**Comment by alphapapa** [comment]
Please provide some basic info like: Emacs version, Magit version, `magit-todos` version, which scanner you're using and which version.

Also, you said it happens in one of your repos.  Do you mean that it only happens in that repo, and not in any others?  If so, it will probably be necessary to look at the to-do items in the repo.

The most direct way to see what the problem is would be to `edebug-defun` on the `magit-todos--line-item` function, and then, when `edebug` activates, get the contents of the scanner output buffer by pressing `e` and eval'ing `(setq scanner-output (buffer-string))`, then you should be able to insert the `scanner-output` variable into another buffer and examine it.

**Comment by lbolla** [comment]
It turns out the problem is that in my repo there are some files which have enormously long lines (they are mechanically concatenated and uglified JS files). Emacs regex parser chokes on them. I've excluded them using `magit-todos-exclude-globs`.

**Comment by alphapapa** [comment]
@lbolla  Thanks.  If you encounter this in any more of your repos, let me know, and maybe I can figure out a way to give a more helpful error message.

**Comment by seanfarley** [comment]
I just ran into this error and was about to report it but found this issue already did. It'd be nice to not have such a esoteric error :-D

**Comment by alphapapa** [comment]
I'll see if I can make the error useful and continue scanning other files.

**Comment by nedijahij** [comment]
I do too get this error. Not sure what is going on:
 
```
error in process sentinel: magit-todos--line-item: Stack overflow in regexp matcher
error in process sentinel: Stack overflow in regexp matcher
```

**Comment by alphapapa** [comment]
@nedijahij See lbolla's comment.

**Comment by BlindingDark** [comment]
You can set max columns if you use rg:
```elisp
(setq magit-todos-rg-extra-args '("-M 120"))
```
```
-M, --max-columns <NUM> 
```

**Comment by nedijahij** [comment]
@BlindingDark i used ag actually.

**Comment by BlindingDark** [comment]
@nedijahij try `-W/--width`

```elisp
(setq magit-todos-ag-extra-args '("-W 120"))
```
