### ISSUE TITLE
Don't bind keys behind my back

### ISSUE THREAD

**Issue by Alexander-Shukaev** [alphapapa/magit-todos#70]
Following #48 and #31, this

https://github.com/alphapapa/magit-todos/blob/14e5347c98f42166ad7061b8663d368bb0d4fba4/magit-todos.el#L336

is very intrusive.  In my case, I don't want any bindings to be present unless I approved them and use them.  In my configuration, I wipe out keymaps for all modes/packages which I use and I redefine their keymaps from scratch the way I like it.  It's fine for the most part except scenarios like this.  Now I have to add a hook to clear the binding that you inject when the mode is activated.  Why don't you create a `defcustom` to enable this (which you can also set to `t` by default if you like it)?

**Comment by alphapapa** [comment]
It's standard for Emacs packages to define keymaps.  In this case, the package consists of a section added to magit-status buffers, which have default key bindings to jump to the sections.  It seems reasonable and expected to add such a key binding to that keymap.  It doesn't conflict with any existing Magit binds, and it saves users from having to do it themselves.

I don't think it's unreasonable to expect an unusual user like yourself to have to take a minor, extra step of overriding that keybinding.  And if you're not actually using that keybinding yourself, it does no harm to have it present.

I don't want to add extra code to do this conditionally, and an extra customization option users will have to sort through and decide whether to modify, for the unusual and rather extreme case of a user who who wipes out all keymaps in all packages and defines them from scratch.  :)

**Comment by Alexander-Shukaev** [comment]
By the way, next time you might decide that you want to inject more such bindings.  I would need to clear those as well then, but for that I have to closely monitor your package upon every upgrade.  You get my point, it simply becomes messy.

**Comment by Alexander-Shukaev** [comment]
I think we're going in circles now.  I will reiterate: the way you implemented key bindings is non-standard.  Comparing EVIL and its adoption, I would say it is much less non-standard than your implementation of key bindings, that's for sure.  Even if your package provides additional functionality for `magit`, that does not make your package an official part of `magit`.  Thus, aggressively injecting your opinionated key bindings into a foreign package in this case is at the very least "rude" to some of the users of both packages.  I don't understand why you have to keep composing all those excuses to cover the approach that does not scale from the beginning on instead of just adding five lines of code which would solve problem once and for all.  By now, you've definitely already spent more time messing around with these three tickets rather than coding those 5 lines of code.  My apologies if that sounds disturbing but your attitude as a package designer to the third issue on the same topic is really surprising.  As we say in the field, your code --- your call...

**Comment by alphapapa** [comment]
I feel like you've been rude in these messages, but in spite of that, I'll assume good faith and give you one more reply.  What I ultimately want is the best technical quality, and I'll assume you do too.

> the way you implemented key bindings is non-standard. 

I disagree.  

1.  There are packages in MELPA that bind keys much more "invasively" than this package does.
2.  The way this package extends Magit is AFAIK somewhat unique.  I don't think it's unreasonable to add one key binding to this special-purpose keymap.

So in one sense it's not non-standard, and in another, there isn't a well-defined standard for this.  You've offered no evidence to the contrary, just your repeated assertion.

> Comparing EVIL and its adoption, I would say it is much less non-standard than your implementation of key bindings, that's for sure. 

I don't understand how you could think that if you understand what EVIL does.  As I said before, it fundamentally changes Emacs's UI paradigm, and it's so invasive that a package exists just to fix compatibility with other third-party packages.

> Even if your package provides additional functionality for magit, that does not make your package an official part of magit.

I haven't claimed otherwise.

> Thus, aggressively injecting your opinionated key bindings into a foreign package in this case is at the very least "rude" to some of the users of both packages.

I disagree.  The fact is that at least hundreds of users, and probably one or two thousand, use this package without any complaints.  A grand total of three, including you, have mentioned this one key binding, and two of them are EVIL users--and I've already addressed EVIL.  

So a grand total of one non-EVIL user has complained about this one key binding.  This one user is not a typical Emacs user, as he wipes out all keymaps and recreates them from scratch.  Despite Emacs's infinite customizeablilty, this is the first I've heard of anyone doing such a thing for one's personal config.  

So this one user suddenly appears here and demands that changes be made to accommodate his preferences, implying that to do otherwise is "aggressive" and "opinionated" and "rude" and "disturbing."  No matter how politely and reasonably the package developer explains his rationale, the user ignores those reasons, claiming the developer is "composing excuses," and insists that the developer is mistreating users by not acceding to his demands.

I think most people would not be surprised if the developer is not receptive to said demands.

> By now, you've definitely already spent more time messing around with these three tickets rather than coding those 5 lines of code.

And you have spent more time here than if you had written the code and submitted a PR.  If you are as knowledgeable of Emacs Lisp as you appear to be, that should be trivial for you.  Instead, you demand that I do work to accommodate your preferences.  That's not how this works.

If you want me to make the changes you want, you need to calmly, politely discuss my stated reasons and convince me that your idea is better.

> My apologies if that sounds disturbing but your attitude as a package designer to the third issue on the same topic is really surprising.

"I'm sorry for what I'm about to say, but [implied insult here]."  Do you know how apologies work?  I see that you're from a different country and culture, but I'm guessing that much is shared.  

Do you see what I mean about being rude?  We have never met before.  I have spent many hours on this project, making it useful and available to others.  Most people who have a suggestion or bug report or problem do so politely, not making demands, and offering some gratitude for what has already been done.  You have done entirely the opposite in three messages now, which is really surprising.  

I think most developers would simply ignore you by this point.  I'm still willing to work with you if you'll change your attitude, but if this is how you're going to be, I'll spend my limited time for this activity working with people who are enjoyable to interact with.  Your call.

**Comment by muihlinn** [comment]
I really do not understand what's going on here - or I do, but 
can't/want get there.

To me, choices are simple once that the developer said no way:

Fork, fix and use it your own. Optionally submit a PR... or forget 
about the package.

There is no need to argue or being harsh, code is public for a 
reason.

--
Best regards.

**Comment by mpereira** [comment]
People landing here from Google, the following should disable `magit-todos`'s evil-conflicting keybindings:

```emacs-lisp
(general-define-key
 :keymaps '(magit-todos-section-map magit-todos-item-section-map)
 "jT" nil
 "jl" nil
 "j" nil)
```

This would ideally be fixed in [evil-collection](https://github.com/emacs-evil/evil-collection/blob/master/modes/magit-todos/evil-collection-magit-todos.el). I might open a PR later.

**Comment by Alexander-Shukaev** [comment]
Does `general` do it at `magit-todos-mode-hook`?  If not, how does it avoid aggressive remapping in `magit-todos-mode`?

**Comment by mpereira** [comment]
@Alexander-Shukaev I'm not sure I understand the question, but here is my personal config which uses the snippet above to disable the evil-conflicting keybindings: https://github.com/mpereira/.emacs.d#magit-todos

**Comment by alphapapa** [comment]
Please, if you want to discuss this further, open an issue on `evil-collection` and discuss it there.  I will not be making these changes here, as discussed.

**Comment by mpereira** [comment]
Sorry for the noise @alphapapa, I was just trying to help.

**Comment by alphapapa** [comment]
No problem!  Thanks.

If you think this should be documented in the readme, please feel free to suggest something.  I don't mind mentioning an aside in the readme for EVIL users, similar to how MacOS is mentioned.  I just don't want to change the package's code for it.
