### ISSUE TITLE
Cannot show TODO item  from Non-org files on Windows

### ISSUE THREAD

**Issue by jinlin82** [alphapapa/magit-todos#72]
Thanks for this great package.

But I cannot show TODO item from Non-org files on Windows.

As Windows issues [#29](https://github.com/alphapapa/magit-todos/issues/29), I use git-grep.
I can get the TODO items from the org-mode files, but I can't get TODO items from other format fils, like markdown files, text files.

I install the package from Melpa, the version is 20190114.1450.
My config:
```
(setq magit-todos-nice nil)
(setq magit-todos-scanner (quote magit-todos--scan-with-git-grep))
(magit-todos-mode)
```

My magit version:
```
Magit 20180519.1008, Git 2.17.0.windows.1, Emacs 26.1, windows-nt
```

**Comment by alphapapa** [comment]
I can't provide help for Windows because I don't use Windows and there is too much variation to account for (e.g. Windows versions, WSL, Cygwin, different Emacs builds, git/rg builds, etc).  Please post in issue #29 and collaborate with the other users who have posted there.  You will have to do more investigation on your end to find the problem.
