### ISSUE TITLE
How to highlight todos in current branch vs. master?

### ISSUE THREAD

**Issue by smaret** [alphapapa/magit-todos#80]
I would like to display the TODOs in the current branch with `git diff master` rather than the default `git diff HEAD^`. How can I do that?

**Comment by alphapapa** [comment]
You can change the command here: https://github.com/alphapapa/magit-todos/blob/master/magit-todos.el#L1214

Why do you want to do this?  That command was chosen specifically because it seems to give the best, most useful results.  If that isn't the case for you or your projects, maybe it should be configurable with an option.

**Comment by smaret** [comment]
I work on the `nixpkgs` projet and it has hundreds of TODOs. When I develop a new package, I usually create a topic branch and then I make several commits in it (typically one for each dependency of the package). Each of this commit may have TODOs that I would like to display in magit.

With the current default (`HEAD^`), `magit-todos` displays only the TODOs in the last commit. I would need to set the default to `master` (or perhaps `HEAD@{1}`) to display the TODOs in all commits in that branch.

I understand that this is my own workflow and other users may have different preferences. So I think that `defcustom` variable to set this would be very useful.

**Comment by alphapapa** [comment]
Thanks for the great explanation.

I refreshed my memory from https://github.com/alphapapa/magit-todos/issues/77#issuecomment-489583676.   I used `HEAD^` because e.g. `master..HEAD` doesn't show new TODOs in the index or working tree.  But I think I didn't test it with a branch that has multiple commits since `master`.

So I think there are two options:

1.  Make the default diff target configurable with an option.
2.  Run both `git diff HEAD^` and `git diff master`, combining the results to get items in all of the branch, index, and working tree.  To avoid performance problems in large repos, this would need to be configurable to do one or the other or both.

What do you think?

Thanks.

**Comment by smaret** [comment]
I think that option 2 is better. In some cases you want to diff with another branch than master depending on your git workflow. For example, you may work to display TODOs in a topic branch that against a `stable`or `release-x.x` branch. Having the diff target configurable with an option (possibly through directory variables) allows you to do that.
