### ISSUE TITLE
Wrong todo detective

### ISSUE THREAD

**Issue by forrestchang** [alphapapa/magit-todos#81]
I have some word in my source code which not todo items, and they show up in magit todo.

For example:

```
;; Set todo Keyworkds
(setq org-todo-keywords
      (quote ((sequence "TODO(t)" "STARTED(s)" "PROJ(p)" "|" "DONE(d)")
              (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)"))))
```

This shows up in magit-todo:

![image](https://user-images.githubusercontent.com/7857126/59422416-edab0e00-8e02-11e9-9a9d-2329cecc7726.png)

I think only check TODOs in comments will be better.

**Comment by alphapapa** [comment]
This is a known issue.  It's not practical to detect only items in comments, because the backend tools (`rg`, `git grep`, `grep`) do not parse files by language.

Early implementations of this package parsed files in Emacs, which allowed distinguishing items in comments, but it was too slow to be generally useful.

However, in the example you gave, the problem could be solved by using `magit-todos-keyword-suffix`.  For example, if you use `TODO:` for your actual task items instead of plain `TODO`, and set the suffix to the default value, items in the code you shared will not be detected as task items.

**Comment by forrestchang** [comment]
@alphapapa Thanks, it works.
