### ISSUE TITLE
magit-todos not working in some of the git repositories

### ISSUE THREAD

**Issue by CsBigDataHub** [alphapapa/magit-todos#98]
Package is also **not** working for some repositories while it's working for some repo's like  `.emacs.d ` repo.

I have a repository with yaml files and `magit-todos-mode` does not show up in `magit-status-buffer` . I get a empty buffer if I run `magit-todos-list`. When I run `ivy-magit-todos`  i  get `nice failed` in mini-buffer .

I have installed `libnice` with `homebrew`.

This is how I have it in yaml file 
![image](https://user-images.githubusercontent.com/23665525/78689697-3e24b800-78bc-11ea-99a4-ca811a47e691.png)

I am using `centaur-emacs` configuration with `emacs 26.3` on macos.

**Comment by alphapapa** [comment]
> Package is also not working for some repositories while it's working for some repo's like .emacs.d repo.

That is not enough information to begin to diagnose the problem.

> When I run ivy-magit-todos i get nice failed in mini-buffer .  I have installed libnice with homebrew.

I don't know what `libnice` on `homebrew` does.  If you think `nice` is the problem, disable the setting.  `M-x customize-group RET magit-todos RET`.

Since you have reported that the package **does work**, probably there is no bug here.  Probably you are having an issue related to using MacOS, or you may not understand something about how the package works.

**Comment by CsBigDataHub** [comment]
@alphapapa , Sorry about that. I figured it out , Looks like its mandatory to have TODO in like

`# TODO:`

in some of my  code I had TODO with out **:** at the end or no space between `#` and `TODO`.
I guess 'hl-todo ' package deals with this.

**Comment by alphapapa** [comment]
@CsBigDataHub If you would do what I suggested, you would find that this is already accounted for.

![mb1](https://user-images.githubusercontent.com/601365/78718420-e00dca00-78e7-11ea-9887-e6e44340a124.png)
